language: rust
cache: cargo
script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo build --verbose --all
  - cargo test --all
  - cargo fmt --all -- --check
  - cargo clippy -- --deny=warnings
